### ISSUE TITLE
User journey: As a user I want to have a clear idea what health information is available on the  Galil Health page 

### ISSUE THREAD

**Issue by hasansaad1** [FACN3/rikaz#2]
Given that I visited the Galil society **Mashrou Siha** page for the first time I would like to have a brief introduction about information available on the website and be able to easily navigate to the smoking page

- [ ] at the top of the page should be the Galil Society Logo
- [ ] below that the name of the page displayed (Mashrou Siha)
- [ ] underneath that, a short introduction to data available #4 
- [ ] show the information for the health on a chart. rel #5 
- [ ] at the bottom, round icons (health status, health behaviour, health services, health literacy, alternative medicine) ( technical ) #20
- [ ] when user presses the **health behaviour** icon, all icons change the content to periodic check ups, smoking, leasure, food and nutrition: #3 
- [ ] the arrow button should be add so the user can come back to the previous menu
